### ISSUE TITLE
game.restart() Crashed the Game

### ISSUE THREAD

**Issue by ZeroHackeR** [cocos/cocos-engine#10705] opened 2022-04-08 10:47 UTC
### Cocos Creator version

3.5.0

### System information

Android

### Issue description

As soon as game.restart(); is called, the game crashed.

### Relevant error log output

Logcat Error Messages: 
`
2022-04-08 17:37:53.302 25453-25471/? E/jswrapper: ERROR: Uncaught TypeError: Cannot read property 'emit' of null, location: src/cocos-js/cc.js:0:0
    STACK:
     - [0]_onTouchEnded@src/cocos-js/cc.js:3
     - [1]emit@src/cocos-js/cc.js:1
     - [2]dispatchEvent@src/cocos-js/cc.js:1
     - [3]dispatchEvent@src/cocos-js/cc.js:1
     - [4]_handleTouchEnd@src/cocos-js/cc.js:1
     - [5]_handleEventTouch@src/cocos-js/cc.js:1
     - [6]dispatchEventTouch@src/cocos-js/cc.js:1
     - [7]dispatchEvent@src/cocos-js/cc.js:1
     - [8]_emitEvent@src/cocos-js/cc.js:1
     - [9]_frameDispatchEvents@src/cocos-js/cc.js:1
     - [10]tick@src/cocos-js/cc.js:1
     - [11]e@src/cocos-js/cc.js:1
     - [12]tick@jsb-adapter/jsb-builtin.js:601
2022-04-08 17:37:53.302 25453-25471/? E/Cocos: 17:37:53 [ERROR]: [ERROR] file /Volumes/Data/Playground/CC3.5/CocosCreator.app/Contents/Resources/resources/3d/engine/native/cocos/application/CocosApplication.cpp: line 140 
2022-04-08 17:37:53.302 25453-25471/? E/Cocos: 17:37:53 [ERROR]: 
    Uncaught Exception:
     - location :  (see stack)
     - msg : Uncaught TypeError: Cannot read property 'emit' of null
     - detail : 
           - [0]_onTouchEnded@src/cocos-js/cc.js:3
     - [1]emit@src/cocos-js/cc.js:1
     - [2]dispatchEvent@src/cocos-js/cc.js:1
     - [3]dispatchEvent@src/cocos-js/cc.js:1
     - [4]_handleTouchEnd@src/cocos-js/cc.js:1
     - [5]_handleEventTouch@src/cocos-js/cc.js:1
     - [6]dispatchEventTouch@src/cocos-js/cc.js:1
     - [7]dispatchEvent@src/cocos-js/cc.js:1
     - [8]_emitEvent@src/cocos-js/cc.js:1
     - [9]_frameDispatchEvents@src/cocos-js/cc.js:1
     - [10]tick@src/cocos-js/cc.js:1
     - [11]e@src/cocos-js/cc.js:1
     - [12]tick@jsb-adapter/jsb-builtin.js:601
2022-04-08 17:37:53.302 25453-25471/? D/jswrapper: JS: [ERROR]: (see stack) Uncaught TypeError: Cannot read property 'emit' of null  - [0]_onTouchEnded@src/cocos-js/cc.js:3
     - [1]emit@src/cocos-js/cc.js:1
     - [2]dispatchEvent@src/cocos-js/cc.js:1
     - [3]dispatchEvent@src/cocos-js/cc.js:1
     - [4]_handleTouchEnd@src/cocos-js/cc.js:1
     - [5]_handleEventTouch@src/cocos-js/cc.js:1
     - [6]dispatchEventTouch@src/cocos-js/cc.js:1
     - [7]dispatchEvent@src/cocos-js/cc.js:1
     - [8]_emitEvent@src/cocos-js/cc.js:1
     - [9]_frameDispatchEvents@src/cocos-js/cc.js:1
     - [10]tick@src/cocos-js/cc.js:1
     - [11]e@src/cocos-js/cc.js:1
     - [12]tick@jsb-adapter/jsb-builtin.js:601
2022-04-08 17:37:53.302 25453-25471/? E/jswrapper: [ERROR] (/Volumes/Data/Playground/CC3.5/CocosCreator.app/Contents/Resources/resources/3d/engine/native/cocos/bindings/jswrapper/v8/Object.cpp, 530): Invoking function (0x7f80dccea0) failed!
2022-04-08 17:37:53.303 25453-25471/? D/jswrapper: ScriptEngine::cleanup begin ...
`

### Steps to reproduce

Just call: game.restart()

**Comment by bofeng-song** [comment] 2022-04-11 03:53
@ZeroHackeR Could you upload your demo，I can`t reproduce the crash while call game.restart().

**Comment by bofeng-song** [comment] 2022-04-11 03:58
@ZeroHackeR My test-case is cloned from here:   https://github.com/cocos-creator/test-cases-3d.git
switch to branch v3.5 and then make sure the start scene is restart.scenne

**Comment by bofeng-song** [comment] 2022-04-11 10:31
@ZeroHackeR Due to enable Swappy, we`ll fix it as soon as possible. 
you can disable it temparaly! 
change directory to  "resources\resources\3d\engine\native" and search "swappy"  then click swappy directory, finally you can see CMakeLists.txt file. Change SWAPPY_ENABLED  to FALSE

**Comment by timlyeee** [comment] 2022-04-14 03:26
That's weird, recent version I didn't meet this problem

**Comment by pandamicro** [comment] 2022-05-05 04:08
@bofeng-song please provide how this crash is related to Swappy

**Comment by bofeng-song** [comment] 2022-05-05 06:46
Swappy has been disabled by default. And we can not reproduce the problem any more.

**Comment by minggo** [comment] 2022-05-06 10:10
@bofeng-song how did you know it is caused by Swappy?

**Comment by bofeng-song** [comment] 2022-05-06 10:28
I reproduce it by enable Swappy, and the crash will disappear while disable Swappy.
While crash, the crash stack point at swappy api calls.

Maybe the newest version has been fix the crash.

**Comment by minggo** [comment] 2022-05-06 10:43
Is the crash log the same as the issue?

**Comment by bofeng-song** [comment] 2022-05-07 00:56
> Is the crash log the same as the issue?

I`ve forgotten. Maybe need to use the same version to reproduce it and get the log

**Comment by minggo** [comment] 2022-05-07 01:43
@bofeng-song  As you can not reproduce the issue, i will close it.
@ZeroHackeR please reopen it if you still have the issue.

**Closed as completed by minggo** 2022-05-07 01:43 UTC
Labels: Bug, P1, Env: Native, Env: Android
