### ISSUE TITLE
Regarding post-processing issues with custom pipelines.

### ISSUE THREAD

**Issue by whaqzhzd** [cocos/cocos-engine#16059] opened 2023-08-21 11:51 UTC
### Cocos Creator version

3.8

### System information

ALL

### Issue description

There are 2 issues, they are: 

1. In the editor, when the global property of the post processing set on the screen is turned off, it is found that it cannot be turned off, and it is not persisted to the scene file. Restarting or switching scenes, the global property is always true.

2. Although the post processing part is added to the passContext in line [178](https://github.com/cocos/cocos-engine/blob/develop/cocos/rendering/post-process/post-process-builder.ts#L178) of the builder, when rendering later, it does not filter out the post processing flows that do not belong to the camera that is currently being rendered. This will lead to rendering errors, as the camera incorrectly uses post processing that does not belong to itself. [renderer](https://github.com/cocos/cocos-engine/blob/develop/cocos/rendering/post-process/post-process-builder.ts#L217)

I'm not sure if [setting-pass](https://github.com/cocos/cocos-engine/blob/develop/cocos/rendering/post-process/passes/setting-pass.ts#L10) is used to filter out illegal post processing, but forcing it to return default here will cause the filtering to fail. 

### Steps to reproduce

-

**Comment by 2youyou2** [comment] 2023-08-28 09:42
1. https://github.com/cocos/cocos-engine/pull/16116 fixed
2. I think the default setting is not the problem since setting-pass will filter the default setting `enable && !!setting && setting.enabledInHierarchy` , and the defaultSetting.enabledInHierarchy is false.
[Check it here](https://github.com/cocos/cocos-engine/blob/develop/cocos/rendering/post-process/passes/setting-pass.ts#L22C16-L22C65)

Did your inherited setting-pass call `super.checkEnable` like [TAAPass](https://github.com/cocos/cocos-engine/blob/develop/cocos/rendering/post-process/passes/taa-pass.ts#L105)?

If you still have problem, please uploading a test project  for reproducing it.

**Comment by whaqzhzd** [comment] 2023-08-28 10:17
> 



> 1. [fixed serialize post process #16116](https://github.com/cocos/cocos-engine/pull/16116) fixed
> 2. I think the default setting is not the problem since setting-pass will filter the default setting `enable && !!setting && setting.enabledInHierarchy` , and the defaultSetting.enabledInHierarchy is false.
>    [Check it here](https://github.com/cocos/cocos-engine/blob/develop/cocos/rendering/post-process/passes/setting-pass.ts#L22C16-L22C65)
> 
> Did your inherited setting-pass call `super.checkEnable` like [TAAPass](https://github.com/cocos/cocos-engine/blob/develop/cocos/rendering/post-process/passes/taa-pass.ts#L105)?
> 
> If you still have problem, please uploading a test project for reproducing it.

Regarding the second issue, consider this scenario:
Camera A has Bloom post-processing, Camera B has Blur post-processing. Object a is rendered by Camera A with Bloom. Object b is rendered by Camera B with Blur.
Given Camera A has higher render priority than Camera B, Camera A renders first. In [getSetting](https://github.com/cocos/cocos-engine/blob/develop/cocos/rendering/post-process/passes/setting-pass.ts#L8) Camera A correctly gets Bloom.
After Camera A rendering is done, now enter Camera B processing flow. First here [passes](https://github.com/cocos/cocos-engine/blob/develop/cocos/rendering/post-process/post-process-builder.ts#L215) traverses all post-processing passes, so passes here contain both Bloom and Blur.
Then during filtering here [setting](https://github.com/cocos/cocos-engine/blob/develop/cocos/rendering/post-process/passes/setting-pass.ts#L21)... Because [getSetting](https://github.com/cocos/cocos-engine/blob/develop/cocos/rendering/post-process/passes/setting-pass.ts#L8) Bloom cannot be obtained here. But below default is forcibly returned.
What would this lead to? It leads to the returned setting having a value, rather than the value obtained from getSetting based on the constructor. This is where the problem occurs.
Have I expressed my meaning clearly?

**Comment by whaqzhzd** [comment] 2023-08-28 10:29
Currently, we add post-processing by calling the insertPass function. The fundamental problem is actually because [here](https://github.com/cocos/cocos-engine/blob/develop/cocos/rendering/post-process/post-process-builder.ts#L206) obtains passes that contain all post-processing existing in the entire game. This array includes Bloom, Blur, and other passes added by default. Then checkEnable is called. It enters the getSetting function to check if the setting exists. The setting itself does not exist in the passContext.postProcess array. However, due to two points. First, [here](https://github.com/cocos/cocos-engine/blob/develop/cocos/rendering/post-process/passes/setting-pass.ts#L10) returns default. Thus causing [here](https://github.com/cocos/cocos-engine/blob/develop/cocos/rendering/post-process/passes/setting-pass.ts#L21) to become invalid. Second, [here](https://github.com/cocos/cocos-engine/blob/develop/cocos/rendering/post-process/post-process-builder.ts#L206) returns the processing of the entire game, rather than the current camera's processing. The combination of these two points produces this BUG.

**Comment by 2youyou2** [comment] 2023-08-29 02:42
The default setting maybe confused, remove it is ok.
Can this pr fixed your problem https://github.com/cocos/cocos-engine/pull/16116?

**Comment by whaqzhzd** [comment] 2023-08-29 03:20
> The default setting maybe confused, remove it is ok. Can this pr fixed your problem #16116?

You can make each camera have its own post processing by simply deleting the default. I've tested it in a custom engine.

**Comment by whaqzhzd** [comment] 2023-08-29 03:27
There is still a bug regarding post processing at this stage. It will cause the Android to show a white screen. I still don't know the reason. I will make a demo for you

**Comment by whaqzhzd** [comment] 2023-08-29 03:58
![image](https://github.com/cocos/cocos-engine/assets/16913061/6c5a1895-3d22-4af7-bfbc-dfe49a8469f2)

This demo is dual camera + dual post processing. One is bloom and the other is blur, any mixed colors rendered on screen. Everything works fine on web. After building Android, it will work normally for the first time or first few restarts. However, subsequent app launches will show a very unique white screen phenomenon. To make this demo work properly, make sure default is deleted in the custom engine. Similar to this [PR ](https://github.com/cocos/cocos-engine/pull/16120). Otherwise the effect will be messy. No clue yet for the Android white screen issue. This demo can also be used to verify whether the default export causes the filtering to fail.

 I've raised this issue on GitHub and look forward to your feedback on it.
[postProcessIssues.zip](https://github.com/cocos/cocos-engine/files/12460121/postProcessIssues.zip)

**Comment by 2youyou2** [comment] 2023-08-29 06:54
Which backend did you use? gles or vulkan?

**Comment by whaqzhzd** [comment] 2023-08-29 06:56
> Which backend did you use? gles or vulkan?

gles

**Comment by 2youyou2** [comment] 2023-08-29 07:23
Build with default setting and restart the app for twenty times. Still can not reproduce this problem.

![image](https://github.com/cocos/cocos-engine/assets/1862402/7b13913b-4c49-4815-8880-9b8a0a5f15ff)

**Comment by 2youyou2** [comment] 2023-08-29 07:24
Which device did you test? Can you try the vulkan backend, vulkan can be more stable.

**Comment by whaqzhzd** [comment] 2023-08-29 07:25
> Which device did you test? Can you try the vulkan backend, vulkan can be more stable.

Let me try ，My device is a Huawei Mate 10.

**Comment by 2youyou2** [comment] 2023-08-29 07:36
I have tried vivo s9, hornor 30 and oneplus 11.  Maybe it's a device related problem?

**Comment by whaqzhzd** [comment] 2023-08-29 07:47
> I have tried vivo s9, hornor 30 and oneplus 11. Maybe it's a device related problem?

I deleted the cache and it seems the problem no longer occurs, so let's just leave it at that. Thanks again
Regarding this issue, I have no other questions left.

**Comment by whaqzhzd** [comment] 2023-08-29 07:54
Regarding the issue I had in the previous demo where I needed to set the render texture size to be the same as the screen myself when using camera render textures, I suggest the engine help the user do this when the width and height of the render texture are both 0. Or you can add a setting for this in the render texture inspector. Of course it also works without adding this and letting users set it themselves, it's just more troublesome. This is just a suggestion.

![image](https://github.com/cocos/cocos-engine/assets/16913061/36afe7a9-47d8-4eca-b5db-898873f33e27)

**Comment by 2youyou2** [comment] 2023-08-29 08:09
Thanks for the suggestion, we will consider it.
Since the problem in this issue is solved, let's close it.

**Closed as completed by 2youyou2** 2023-08-29 08:09 UTC
Labels: Bug, Needs Triage
