### ISSUE TITLE
Logic error for normal ccclass subclasses

### ISSUE THREAD

**Issue by smallmain** [cocos/cocos-engine#14550] opened 2023-03-12 06:48 UTC
### Cocos Creator version

3.7.1

### System information

Mac

### Issue description

```ts
@ccclass("A")
export class A {
    // ...
}

@ccclass("B")
export class B extends A {
    // ...
}

@ccclass
export class C extends Component {
    @property(B)
    v: B = new B();
}
```

If it is the above code at the beginning, then the data in the prefab is like this:
```json
{
  "__type__": "B",
}
```

If I change the type of attribute v to A:

```ts
@ccclass
export class C extends Component {
    @property(A)
    v: A = new A();
}
```

and then manually save the prefab data, but the data type will not change, it is still B. 

If I delete B class, an error will be reported at this time, because B in data, but A is actually referenced.

### Steps to reproduce

.

**Comment by jareguo** [comment] 2023-08-11 04:59
> and then manually save the prefab data, but the data type will not change, it is still B.

This is normal and as expected, since B is-a A. Other engines do the same.

> If I delete B class, an error will be reported at this time, because B in data, but A is actually referenced.

Yes, because the deserialization failed and the original data doesn't match. The engine doesn't think it should automatically convert the object to type A here at such times. Because the type itself has value to the logic, changing it arbitrarily is likely to cause unintended behavior.

**Comment by smallmain** [comment] 2023-08-11 06:27
> > and then manually save the prefab data, but the data type will not change, it is still B.
> 
> This is normal and as expected, since B is-a A. Other engines do the same.
> 
> > If I delete B class, an error will be reported at this time, because B in data, but A is actually referenced.
> 
> Yes, because the deserialization failed and the original data doesn't match. The engine doesn't think it should automatically convert the object to type A here at such times. Because the type itself has value to the logic, changing it arbitrarily is likely to cause unintended behavior.

Not that an automatic conversion is needed:
- Since the datatypes don't match, the serialization fails, shouldn't it at least give a warning?
- The old data will always be in the prefab, even if it is modified to type A and then saved, is that right?
- The component keeps reporting an error if type B is removed, and clicking Reset Component doesn't fix the error other than removing the component, but the user didn't do anything wrong except change the property from type B to type A , why need the user to lose all other attribute information (because the component needs to be removed), just to solve this "error"?

**Comment by jareguo** [comment] 2023-08-12 03:40
> * Since the datatypes don't match, the serialization fails, shouldn't it at least give a warning?

If a class does not exist, the serialization will just save it as null property. And inspector should become error. If not error then it's a bug.

> * The old data will always be in the prefab, even if it is modified to type A and then saved, is that right?

If all class exist. Yes. Since B extends A, so users should use any sub-class of A as they need.

> * The component keeps reporting an error if type B is removed

I think it's a bug. @arsen2010 must have a look at it.

**Comment by smallmain** [comment] 2023-08-12 15:02
@jareguo 

> If all class exist. Yes. Since B extends A, so users should use any sub-class of A as they need.

No, I think the warning should be given regardless of whether the class exists or not.

Consider this scenario:

- There are still two classes A and B.
- At the beginning:
```
@ccclass("A")
export class A {
    // ...
}

@ccclass("B")
export class B extends A {
    // ...
}

@ccclass
export class C extends Component {
    @property(B)
    v: B = new B();
}
```
- Assuming that A and B are not written in the same file, one day the component no longer supports B and changes it to A.
```
@ccclass
export class C extends Component {
    @property(A)
    v: A = new A();
}
```
However, the data in the prefab is still:
```
{
  "__type__": "B",
}
```
In the code, the user has something like this:
```
if(getClass(v) === A){ 
    // ...
}
```
It should pass, but fails because the datatype in the prefab is still B.

So far, the engine has not reported any errors or warnings, correct?

Now there are two kinds of users, one is users who have studied the mechanism of prefab to at least the point like me, they try to open the prefab, and then press save to fix this kind of error. No effect. It can only be solved by removing components.

Another kind of users who don't understand at all can't figure out why this kind of problem occurs. so strange.

Like this kind of error, always give up solving it with "we can't check all the associated prefabs every time we save it?", I think at least one parallel thread can be used to analyze slowly in the background, right? Needless to say, it takes time to troubleshoot this strange error, but it can only be known when the prefab is opened.

- By the way, i just tested it, even if it is not an inherited class, there will still be the above problems:
```
@ccclass("A")
export class A {
    // ...
}

@ccclass("B")
export class B extends A {
    // ...
}

@ccclass("C")
export class C {
    // ...
}

@ccclass
export class C extends Component {
    @property(B)
    v: B = new B();
}
```
Changed B to C, no problem, no errors or warnings, but the prefab data still is B (two class properties were consistent when I tested, not sure can recurrent if classes have different properties).

**Comment by arsen2010** [comment] 2023-08-13 04:10
I think i get the most of points of your two guys talk above：
1、The value of property name 'v' in prefab file data, would not change or console any warn information, when modify the definition 'v' ( switch type A to B , or B to A).
2、Reset or modify the component 'C' in inspector and then save the prefab, it would not update the correct type of ‘v’.
3、Remove the Class B , open the scene with C prefab node, it finally report the error.

![image](https://github.com/cocos/cocos-engine/assets/13517177/245f5fe7-2f87-4865-bc2d-42a2f93f5398)
![image](https://github.com/cocos/cocos-engine/assets/13517177/3c5a0c9c-e6ea-4d9f-a099-2b083afecab7)
![image](https://github.com/cocos/cocos-engine/assets/13517177/b170c75e-68b6-464d-a657-5bd545d4cd5e)
![image](https://github.com/cocos/cocos-engine/assets/13517177/57965ab2-fc07-4a9b-9a76-f069bf00ad67)

The point 1 is the key of points 2 and 3, the data of scene and prefab file would not change with the script component file immediately.

So point 2 the ‘modify‘ operation it is not a bug，maybe it can be better use  ``` parallel thread can be used to analyze slowly in the background``` .
But ’reset‘ operation can not update the correct data, it is a bug definitely.

![image](https://github.com/cocos/cocos-engine/assets/13517177/5307e437-5a32-449a-8900-bcf37727ec71)

Point 3 is normal function. ( when the reset operation is normal too, the error would be reported once.)

-------
so far，the ’reset‘ operation in point 2 as bug would be fixed in v3.8.1

**Comment by smallmain** [comment] 2023-08-13 04:37
@arsen2010 
Basically correct, but one thing is not mentioned:
After modifying the type of "v", the script and the data in the prefab are no longer correct, which will lead to serious errors, similar to:
```
if(getClass(v) === A){ 
    // ...
}
```
But the user is completely unaware, and the editor doesn't give a warning, I don't expect "parallel thread can be used to analyze slowly in the background" to come anytime soon, so it should at least give a warning when the prefab is opened.
repeat again, that in my last test, this problem occurs even if it is not an inherited class.

**Comment by jareguo** [comment] 2023-08-13 15:00
> It should pass, but fails because the datatype in the prefab is still B.

This has nothing to do with the serialization mechanism, it's a very pure programming problem. If you want to include subclasses when determining type, you should have used instanceof.

> Changed B to C, no problem, no errors or warnings, but the prefab data still is B (two class properties were consistent when I tested, not sure can recurrent if classes have different properties).

@arsen2010 The property inspector should be displayed in red.

> Changed B to C, no problem, no errors or warnings, but the prefab data still is B (two class properties were consistent when I tested, not sure can recurrent if classes have different properties).

We'll do a type check on deserialization afterwards to try to output some information. But it doesn't change the pre-existing logic of serialization and deserialization, and there's still the issue of compatibility handling on the user side to consider. Thanks for your feedback.

**Comment by smallmain** [comment] 2023-08-13 15:59
@jareguo 
Is there something wrong with my expression?Of course I know the difference between instanceof and ===.

What I want to say is that when A is written in the script, because the prefab is outdated data, it is B at runtime, and there is no warning and no error in the engine.

Although I can't understand that it is still allowed to save the type as B or other outdated types when the prefab data is saved when the user has changed the type of the script from B to C. (Again, in my tests, C is not necessarily a subclass, it may be a completely unrelated class that also will have this situation)

At least I'm glad we've agreed that at least a warning message should be given. Instead of just fixing the behavior when Reset is hit.

**Comment by jareguo** [comment] 2023-08-14 13:03
> What I want to say is that when A is written in the script, because the prefab is outdated data, it is B at runtime, and there is no warning and no error in the engine.

This is also expected inside other engines, otherwise it would not be possible to use subclasses.

Subclasses are commonly used in components and resources, and the user is perfectly capable of dragging in any subclassed component or subclassed resource. (For example, if type is declared as Component / Asset, then it is possible to drag in any component or resource.) Should there be a warning in this case? Obviously there shouldn't be any warning.

From a programming point of view, once a user has done type inheritance, it should be clear that this is strong parent-subclass coupling, and that subclassing is-a parent, and that it is likely that the subclass will be used wherever the parent class is declared.  This is also a dependency-induced approach, where the user just enters the value of the object, and doesn't really worry about what behavior the object will have for what type it is.

Indeed if dragging and dropping is not possible, then at this point the type will often be dynamically injected by a plugin or during the lifecycle script (e.g. onRestore / resetInEditor), or simplify initialized by any setter. 

Therefore, 兜底 by the editor is not a very proper approach here. At least it is rather a nuisance for a lot of users who really want to use design patterns such as polymorphism, dependency causing, factory functions, etc.

> Although I can't understand that it is still allowed to save the type as B or other outdated types when the prefab data is saved when the user has changed the type of the script from B to C. (Again, in my tests, C is not necessarily a subclass, it may be a completely unrelated class that also will have this situation)

 As stated many times before, this is the kind of problem we will deal with.

**Comment by smallmain** [comment] 2023-08-14 13:17
> otherwise it would not be possible to use subclasses.

This makes sense, but for the situation just now, unlike the resource properties that can be dragged, the user actually has no way to explicitly set the subclass, except to use the initial value, but it is rare, and it is more confusing.

If it is possible to have something like "value:(B)" to inform the user of the type actually stored in the data when the type in the prefab data is inconsistent with the script type and it is determined that the type is a subclass, that would be great alright.

**Comment by jareguo** [comment] 2023-08-14 16:05
Your advice is good. Perhaps a compromise would be to show the class name directly on this UI.
When attribute v is declared with any specific type, the current using class name is displayed with it, e.g. here it should be displayed as v: B
![](https://user-images.githubusercontent.com/13517177/259968929-245f5fe7-2f87-4865-bc2d-42a2f93f5398.png)

**Closed as completed** 2023-09-05 08:06 UTC
Labels: Bug, Information needed, Module: Inspector

**Comment by arsen2010** [comment] 2023-09-07 06:22
In v3.8.2 we fix this bug and optimize some operation.
1、Initial data
![QQ截图20230907141609](https://github.com/cocos/cocos-engine/assets/13517177/f958b180-9d89-4a40-b8f2-59cf4ea2c957)
2、Change data and the new interface of inspector，you can reset the property
![QQ截图20230907141658](https://github.com/cocos/cocos-engine/assets/13517177/f2002e56-1908-43b0-9d6e-524416399885)
3、After reseting，you can save the scene with the correct data.
![QQ截图20230907141825](https://github.com/cocos/cocos-engine/assets/13517177/9c64daec-e680-4562-ae16-f3eff3d7c025)

4、If the initial data set the property 'e' with  B ，and then change ‘e’ type to A，since B extend A ，so the inspecter interface would be normal.

5、If change to other Class without any extension relations, the inspector interface would show reset button.

**Comment by jareguo** [comment] 2023-12-08 03:59
> 4、If the initial data set the property 'e' with B ，and then change ‘e’ type to A，since B extend A ，so the inspecter interface would be normal.

这里无图，根据反馈，应该是实现上有问题，需要进行确认：
当 B 实例赋值到 e （type 声明为 A）上时，属性检查器应该显示成 e: B 而不是 e: A
