### ISSUE TITLE
CC 3.5.0 - Opacity = 0 (invisible), still causes a Drawcall

### ISSUE THREAD

**Issue by Ronsku** [cocos/cocos-engine#11210] opened 2022-05-24 11:52 UTC
### Cocos Creator version

3.5.0

### System information

Windows 11, Chrome

### Issue description

In CC2 when you put something to opacity = 0 it didn't cause a drawcall. In CC3 this is not the case. It only works by disabling the node. Using opacity is in many times more comfortable than disabling a node. Also having a node disabled by default won't run the attached components.
![image](https://user-images.githubusercontent.com/7983358/170027651-e5e5c965-4cc9-4577-9f35-6b04aae23775.png)
Here you see a 255 opacity apple and a banana. This causes 3 drawcalls (since the drawcall text output itself is a drawcall)
![image](https://user-images.githubusercontent.com/7983358/170027823-3381608a-40c6-4020-bf4c-12beb5ee4517.png)
Hiding the node with opacity = 0
![image](https://user-images.githubusercontent.com/7983358/170027893-950acf27-b306-479e-b8c1-db978c4d7474.png)
Does not remove the drawcall like it did in CC2.
![image](https://user-images.githubusercontent.com/7983358/170027978-a4e6bc59-4c7c-46c8-8f11-fadd00edb7f1.png)

### Steps to reproduce

Place opacity = 0 on a node containing a sprite or something that causes a drawcall, it will be invisible but still cause a drawcall that reduces the performance.

### Minimal reproduction project

Demo from above description
[drawcall-test.zip](https://github.com/cocos/cocos-engine/files/8762367/drawcall-test.zip)

**Comment by pandamicro** [comment] 2022-05-26 10:49
We haven't been ruling out draw calls for zero opacity objects, by design, inactive node or disabled component won't be rendered. We are trying to avoid too many checks in the renderer, but we will consider it. @holycanvas please take a look

**Comment by Ronsku** [comment] 2022-05-27 15:17
@pandamicro 
Thanks for your response. I was guessing so, but it was awesome that it didn't cost drawcalls in CC2 when somethign was opacity = 0, because it helped keeping the games performant. There are many benefits of using opacity = 0 instead of disabling the whole node.

I just happened to read this forum topic also just a second ago
https://discuss.cocos2d-x.org/t/scrollview-optimization-v3-5-0/56134
This discusses the same things.

Anything that the engine can do to reduce drawcalls and boost performance automatically is a huge benefit. I'm struggling a bit to make CC3 games running with good performance even though it should have better performance than CC2.

I even created a component that runs an update loop checking if opacity = 0 and disables the node, otherwise enables it. Pretty ugly and hacky but helps.

I will do some more testing as well, but feels I'm getting multiple drawcalls as well even though I'm outputting images from same atlas (but this is outside of this ticket's scope)

**Comment by Ronsku** [comment] 2022-05-28 20:51
The same way if something is invisible with opacity = 0, would it be possible to detect if something is hidden by another graphic, especially in 2D?

Let's say you have 100 drawcalls and place a fullscreen image above it without transparency. Imagine if that would cause drawcalls to go down to 1 :)

Is it possible?

**Comment by AndroidSix** [comment] 2022-10-14 03:40
Guys, can you fix this problem first? I urgently need to merge and enable the latest version of cocos in the new project

**Comment by jareguo** [comment] 2022-10-15 09:43
Sorry about the scheduling, this issue is expected to be fixed in 3.7.1

**Comment by AndroidSix** [comment] 2022-12-14 01:24
Hopefully this issue will be resolved in 3.7.1. 2d multi-node implementations are currently implemented by hiding nodes, which consumes additional performance and interrupts part of the logic.

**Comment by Ronsku** [comment] 2023-02-02 13:54
Thanks a lot, looking forward to 3.7.1! :)

**Comment by LinYunMo** [comment] 2023-03-01 11:06
Sorry for the delay, this issue has been resolved and merged in 3.7.2, you can also refer to this PR to make changes
https://github.com/cocos/cocos-engine/pull/14381
@Ronsku @17628673421

**Closed as completed by LinYunMo** 2023-03-01 11:06 UTC
Labels: P1, Optimization, Module: 2D

**Comment by Ronsku** [comment] 2023-03-01 11:34
Amazing job @LinYunMo!
Thank you everyone involved! ❤️

**Comment by AndroidSix** [comment] 2023-03-02 01:12
Thanks for fixing this, look forward to 3.7.2
