### ISSUE TITLE
[BUG] SpriteAtlas animation weird vibration

### ISSUE THREAD

**Issue by jakebooyah** [cocos/cocos-engine#1963] opened 2017-09-06 13:28 UTC
Using v1.6.1 Cocos Creator, I noticed there’s a slight vibration on the animation that uses sprite from sprite atlas packed with texture packer.

The bug occurs on:
- iOS chrome
- iOS safari
- iOS native

It is fine on:
- dekstop browser
- creator simulator

Please have a look at my test project:
[testSpriteAtlas.zip](https://github.com/cocos-creator/engine/files/1281191/testSpriteAtlas.zip)

**Comment by jareguo** [comment] 2017-09-06 13:34
Thanks. This bug is caused by https://github.com/cocos2d/cocos2d-x/issues/17099 
We will fix it as soon as cocos2d-x get fixed.
You can temporarily fix it in this way http://forum.cocos.com/t/topic/40483/50?u=jare

**Comment by jakebooyah** [comment] 2017-09-25 06:35
@jareguo When I look through the issue and solution link you provided, noticed they are all native focused. Is there a solution for iOS Safari and Chrome?

**Comment by jareguo** [comment] 2017-09-25 06:39
You can modify the `POSITION_TEXTURE_COLOR_FRAG` and `POSITION_TEXTURE_COLOR_VERT`
in CCShader.js

**Comment by jakebooyah** [comment] 2017-09-25 08:31
Thanks @jareguo, it works. Which version will have the fix?

**Comment by jareguo** [comment] 2017-09-25 08:41
It should be fixed before 1.8

**Closed as completed** 2018-10-25 08:08 UTC
