### ISSUE TITLE
[Bug][Spine Skeleton] Rotate the node contains Skeleton broke the animation on emulator or real devices.

### ISSUE THREAD

**Issue by thinhlv** [cocos/cocos-engine#9443] opened 2021-10-07 08:53 UTC
### Creator version?（版本号）
3.3.1

### Affected platform?（受影响的平台）

Emulator, Android, iOS
### How to reproduce?（如何重现）
- Create empty project 2d or 3d
- Import any spine animation to project
- Drag spine to the scene, select the node that contains Skeleton dropped.
- On animation, chose any animation to play.
- On CAHE_MODE select SHARED_CACHE or PRIVATE_CACHE
- Change the node rotation by set Z rotate to any value but not 0 or 180 (or use script to set node.angle to that value).
- Hit run on emulator, and see the result.
- The result animation will be deformation. At 90 and 270 degrees the animation completely disappeared.

### Demo project?（demo 项目）

![demo2](https://user-images.githubusercontent.com/18746281/136355157-a574cce8-0bb7-412b-bf32-0bb1c805e38d.PNG)
![demo](https://user-images.githubusercontent.com/18746281/136354795-dfb30f66-6d21-433f-b0f2-343cb7375b22.PNG)

**Comment by mrnobita** [comment] 2021-10-07 09:43
me too

**Comment by yeshao2069** [comment] 2021-10-08 02:43
Thanks for the feedback, I tested it briefly and didn't find this problem.
I ran it in the simulator in the editor with four different angles set to 0, 90, 180 and 270 and it showed no problem. I'll provide my test demo, do you refer to it and your test is the same usage ?
[NewProject_1.zip](https://github.com/cocos-creator/engine/files/7308103/NewProject_1.zip)

**Comment by yeshao2069** [comment] 2021-10-08 02:47
web
![image](https://user-images.githubusercontent.com/14273437/136490128-69df63de-1649-46e2-8f2d-31e7a1fabf9a.png)

cocos Emulator
Emulator
![image](https://user-images.githubusercontent.com/14273437/136490259-560f7992-3ac5-4217-b49a-5cbaa3d9d5bc.png)

**Comment by thinhlv** [comment] 2021-10-08 03:09
hi, @yeshao2069 
The SHARED_CACHE must be enabled then the issue will be occurred.
There is your sample project but the animation is on SHARED_CACHE mode
[NewProject_1_SHARED_CACHE.zip](https://github.com/cocos-creator/engine/files/7308217/NewProject_1_SHARED_CACHE.zip)
.

**Comment by thinhlv** [comment] 2021-10-08 03:13
![image](https://user-images.githubusercontent.com/18746281/136492560-30b385e5-704e-4013-8111-2a849facc3e6.png)

**Comment by yeshao2069** [comment] 2021-10-08 07:02
If i switch to SHARED_CACHE, it does show an exception, this I let the relevant engineers to check it, this may be a bug

**Comment by yeshao2069** [comment] 2021-10-09 03:41
This is a bug that has been fixed in the latest develop version 3.4.0. Currently, you can merge PR if you need it urgently and remember to recompile the engine.
https://github.com/cocos-creator/engine-native/pull/3884

**Comment by thinhlv** [comment] 2021-10-09 03:55
Thank you! I noted that.

**Comment by yeshao2069** [comment] 2021-10-09 07:49
Also, when verifying this issue, don't use cocos emulator to verify this issue for now, because there may be problems. It is recommended to verify this issue on android or ios.
Because currently there may be some problems (known issues) on cocos emulator in some cases, and we are already arranging to fix these problems.
Attach a screenshot of my test on android for reference.
![8D2EF45E456452E36F2D713C2C1C3D7C](https://user-images.githubusercontent.com/14273437/136649466-e14b5562-063f-4a58-aeb8-b40571da3ecc.jpg)

The issue is closed for now.

**Closed as completed** 2021-10-09 07:52 UTC
