### ISSUE TITLE
Layout not taking scale into consideration

### ISSUE THREAD

**Issue by cocosftw** [cocos/cocos-engine#1980] opened 2017-09-14 03:27 UTC
cc.layout width and height doesnt resize accordingly if the child nodes are not of scale 1.

**Comment by jareguo** [comment] 2017-09-14 03:39
I don't think it should be fixed. Because the entire ui system in Creator dose not support rotation or scaling. This behave can make the engine more concise and efficient. If you really need scaling, don't use cc.Layout and just compute the layout by yourself. It will not be a big challenge if you refer to the source of cc.Layout.

**Closed as completed by jareguo** 2017-09-14 03:39 UTC

**Comment by jareguo** [comment] 2017-09-14 03:41
@knoxHuang please add some comment to the API and Manual so users will understand that these behave is by design.
