### ISSUE TITLE
Custom compressed textures feature does not support texture compression tools that use relative paths

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#14097] opened 2023-01-28 03:50 UTC
### Cocos Creator version

3.6.2

### System information

windows10

### Issue description

Custom compressed textures feature does not support texture compression tools that use relative paths
自定义压缩纹理功能无法支持使用相对路径的纹理压缩工具

### Relevant error log output

![图片](https://user-images.githubusercontent.com/35944775/215240785-4e519432-85c5-433a-978b-04b5914481a4.png)

### Steps to reproduce

-

### Minimal reproduction project

-

**Comment by pandamicro** [comment] 2023-02-11 15:21
@yanOO1497 if the issue is fixed, please close it

**Closed as completed** 2023-02-14 03:29 UTC
Labels: Bug, Module: Build
