### ISSUE TITLE
Cocos Creator 3.7 does not update imported sprite sheets 

### ISSUE THREAD

**Issue by CodeAndWeb** [cocos/cocos-engine#14247] opened 2023-02-15 09:47 UTC
### Cocos Creator version

3.7

### System information

macOS 13

### Issue description

Cocos Creator 3.7 does not update sprite sheets when they are updated. Only the texture changes but the sprite frames are not. This breaks the sprites in the scene, inspector and assets view.

When entering Cocos Creator, sprite sheets are re-loaded and updated. Sprites are correctly displayed in the Assets list and scene view. Sprite properties are updated in the Inspector.

### Steps to reproduce

Extract the files in the attached zip: [Archive.zip](https://github.com/cocos/cocos-engine/files/10741636/Archive.zip)

Add the **contents** of the sheet1 folder to a new empty 2d project.

![image](https://user-images.githubusercontent.com/716009/218992079-08055038-abec-45fc-ba3c-476a7cd2ec81.jpeg)

Everything looks fine, so far.

Open the file system folder of the project and replace the sheet.plist and sheet.png with the files from the sheet2 folder.

Go back to Cocos Creator. The texture is updated but most sprite frames are now broken:

![image](https://user-images.githubusercontent.com/716009/218992192-1465e611-a617-4821-a60f-d43438bfb7ea.jpeg)

With this it’s not possible to update sprite sheets anymore.

Using Reimport asset does not fix the issue.

### Minimal reproduction project

See error description.
All files required for reproducing the issue are there.

**Comment by LinYunMo** [comment] 2023-03-13 05:51
Thank you for your feedback.
This issue was caused by a problem with our sprite sheets importer, which we have fixed in 3.7.1 and released.

**Closed as completed by LinYunMo** 2023-03-13 05:51 UTC
Labels: Bug, Module: AssetSystem, Module: 2D, Editor
